spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:lolsearch
    username: fastcampus
    password: fastcampus

  thymeleaf:
    cache: false

  data:
    elasticsearch:
      cluster-nodes: localhost:9300

#elasticsearch:
#  clustername: elastic
#  host: localhost
#  port: 9300

apiKey: RGAPI-46c04c3f-4650-4d19-a802-2da713d357d4

summonerPath: https://kr.api.riotgames.com/lol/summoner/v3/summoners/by-name/

matchListPath: https://kr.api.riotgames.com/lol/match/v3/matchlists/by-account/

matchPath: https://kr.api.riotgames.com/lol/match/v3/matches/

championPath: https://kr.api.riotgames.com/lol/static-data/v3/champions/

leaguePositionPath: https://kr.api.riotgames.com/lol/league/v3/positions/by-summoner/
