spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/lolsearch
    username: fastcampus
    password: fastcampus

  data:
    elasticsearch:
      cluster-nodes: localhost:9300