spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:lolsearch
    username: fastcampus
    password: fastcampus

  thymeleaf:
    cache: false

apiKey: RGAPI-6d3c449f-b929-4a3e-829c-597035b76432

summonerPath: https://kr.api.riotgames.com/lol/summoner/v3/summoners/by-name/

matchListPath: https://kr.api.riotgames.com/lol/match/v3/matchlists/by-account/

matchPath: https://kr.api.riotgames.com/lol/match/v3/matches/

championPath: https://kr.api.riotgames.com/lol/static-data/v3/champions/

leaguePositionPath: https://kr.api.riotgames.com/lol/league/v3/positions/by-summoner/
