spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:shoppingmall
    username: fastcampus
    password: fastcampus

  thymeleaf:
    cache: false